---
- name: stop iis service
  ansible.windows.win_dsc:
    resource_name: service
    name: W3Svc
    state: stopped

- name: start iis service
  ansible.windows.win_dsc:
    resource_name: service
    name: W3Svc
    state: Running
    startuptype: Automatic
