---
- name: failover prereqs
  hosts: all
  roles:
    - oatakan.windows_cluster.join_domain
    - oatakan.windows_cluster.failover_common

- name: create failover cluster on first node
  hosts: "*cluster_first"
  roles:
    - role: oatakan.windows_cluster.failover
      failover_first_node: true

- name: join failover clusters on other nodes
  hosts: "*cluster_other"
  roles:
    - role: oatakan.windows_cluster.failover
      failover_first_node: false
