---
- name: prereqs
  hosts: "*cluster_first:*cluster_other"
  pre_tasks:
    - name: set ip address of windows ad
      ansible.builtin.set_fact:
        dns_servers: "{{ hostvars['windows_ad_server']['ip_address'] }}"
      when:
        - "'windows_ad_server' in play_hosts"
        - hostvars['windows_ad_server']['ip_address'] is defined
  roles:
    - oatakan.windows_cluster.join_domain
    - iis_dsc
    - oatakan.windows_cluster.failover_common

- name: Create failover cluster on first node
  hosts: "*cluster_first"
  roles:
    - role: oatakan.windows_cluster.failover
      failover_first_node: true

- name: Join failover clusters on other nodes
  hosts: "*cluster_other"
  roles:
    - role: oatakan.windows_cluster.failover
      failover_first_node: false
